# Generated by Django 5.0.6 on 2024-06-17 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Residente', 'Residente'), ('Becario', 'Becario'), ('Adscrito', 'Adscrito')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('cedula', models.CharField(max_length=50)),
                ('firma_electronica', models.ImageField(blank=True, null=True, upload_to='firma_electronica/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medico.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('numero_expediente', models.CharField(max_length=100)),
                ('motivo_solicitud', models.TextField(max_length=500)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('estado', models.CharField(choices=[('Solicitud', 'Solicitud'), ('En revisión', 'En revisión'), ('Listo para enviar', 'Listo para enviar'), ('Enviado', 'Enviado')], default='Solicitud', max_length=20)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medico.especialidad')),
                ('medico_adscrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumenes_por_adscrito', to='Medico.doctor')),
                ('medico_becario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumenes_por_becario', to='Medico.doctor')),
                ('medico_residente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumenes_por_residente', to='Medico.doctor')),
                ('ultimo_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_editados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('Solicitud', 'Solicitud'), ('En revisión', 'En revisión'), ('Listo para enviar', 'Listo para enviar'), ('Enviado', 'Enviado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('Solicitud', 'Solicitud'), ('En revisión', 'En revisión'), ('Listo para enviar', 'Listo para enviar'), ('Enviado', 'Enviado')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='Medico.resumen')),
            ],
        ),
    ]
