# Generated by Django 5.0.6 on 2024-06-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0003_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='medico_adscrito',
        ),
        migrations.AddField(
            model_name='resumen',
            name='medico_adscrito',
            field=models.ManyToManyField(blank=True, related_name='resumenes_por_adscrito', to='Medico.doctor'),
        ),
    ]
