# Generated by Django 5.0.6 on 2024-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0004_remove_resumen_medico_adscrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
