# Generated by Django 5.0.6 on 2024-07-02 00:45

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0005_resumen_fecha_modificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
