# Generated by Django 5.0.6 on 2024-08-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0006_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumen',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
