# Generated by Django 5.0.6 on 2024-09-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0009_alter_doctor_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medico.especialidad'),
        ),
    ]
