# Generated by Django 5.0.6 on 2024-09-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0010_alter_asignacion_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
